### ISSUE TITLE
Problem with nufft in octave

### ISSUE THREAD

**Issue by iimog** [JeffFessler/mirt#26]
Thanks for this amazing toolbox!
I encountered a problem, when I tried to use `nufft` in Octave 7.1.0.
```
nufft 19: Starting nufft() self test; after a wait, shows small errors
nufft 37: err alf1 0.00553546 best 0.000491849
warning: inline is obsolete; use anonymous functions instead
error: 't' undefined near line 1, column 23
error: called from
    feval>@<anonymous> at line 1 column 6
    feval at line 34 column 10
    subsref at line 44 column 14
    nufft_alpha_kb_fit at line 38 column 12
    nufft_init at line 171 column 31
    nufft_table_init at line 38 column 4
    nufft_init at line 94 column 5
    nufft at line 66 column 8
```
I was able to track this problem down, to this line: https://github.com/JeffFessler/mirt/blob/b7f36cc46916821e8bc8502301b1554ebc7efe1d/nufft/nufft_alpha_kb_fit.m#L37

Just changing `inline` to `handle` there, solves the problem for me.

**Comment by iimog** [comment]
An alternative fix, if `inline` needs to be kept is to change the `t` to an `x` in lines 36 and 45 here:
https://github.com/JeffFessler/mirt/blob/b7f36cc46916821e8bc8502301b1554ebc7efe1d/nufft/kaiser_bessel_ft.m#L36-L45

**Comment by JeffFessler** [comment]
Thanks for reporting the issue.  I am going with your alternative because at least for now 'inline' is still supported by both octave and matlab.  After merging I will close this issue and #27.  But when the day comes that one or both stop supporting `inline` then we can excise it completely from the code here.
BTW I am not putting in much effort to support octave anymore because I am focusing on Julia instead, but this was an easy fix so happy to help.

**Comment by JeffFessler** [comment]
Feel free to submit other PRs to help with octave support!

**Comment by iimog** [comment]
Awesome, thank you!
I personally prefer Julia, as well. But currently, I'm working on some existing Matlab code that uses `mirt`. That it is possible to run that code in octave is extremely valuable for me. So thanks again!
